### ISSUE TITLE
Change license headers in code from GPL to APACHE

### ISSUE THREAD

**Issue by koch86** [OpenIKEv2/libopenikev2_impl#6]
According to your last commit, the license of the project was changed from GPL to Apache.
I greatly appreciate that change (and of course your work), since this would enable me to use the library in my project.

Unfortunately only the license files have been changed but not the source code headers themselves, which means I´m still not allowed to use the library since our project policy prefers the licenses in the code.

**Comment by koch86** [comment]
Addition: The same issue exists in libopenikev2 and openikev2

**Comment by alejandro-perez** [comment]
Thanks. Closed with 17ce91de009e66d857539beb6a7173e31123435b

It's also been fixed in the other two repositories.

**Comment by koch86** [comment]
Thank you very much for the quick response and your change! :-)
Unfortunately not all files have been updated - did you miss them or is there any other reason?

E.g. in libopenikev2 there are some files left:
https://github.com/OpenIKEv2/libopenikev2/blob/master/src/authenticator.h
https://github.com/OpenIKEv2/libopenikev2/blob/master/src/childsacollection.h
...
Same applies for the other two projects.
Would you mind also changing the remaining files?

Thanks for your effort and stay healthy!

**Comment by alejandro-perez** [comment]
Right, apparently not all the headers had the same format and I was too lazy to check :).
I've pushed a new commit that should fix it (also in libopenikev2)
